# Generated by Django 5.1.15 on 2026-01-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='0 = Free delivery for this product', max_digits=10, verbose_name='Shipping / Delivery Charge'),
        ),
    ]
