# Generated by Django 5.1.15 on 2026-02-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_window_days',
            field=models.PositiveIntegerField(default=10, help_text='Number of days customer can return this product after delivery (0 = no return allowed)', verbose_name='Return Window (days)'),
        ),
    ]
